files:
  - source: /docs/**/*.md
    ignore:
      - '*.es.md'
      - '*.fr.md'
      - '*.zh.md'
      - '*.it.md'
      - '*.ja.md'
      - '*.pt.md'
      - '*.en.md'
      - '*.sv.md'
      - '/docs/release_notes/8.5.md'
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
    update_option: update_as_unapproved
