files:
  - source: /docs/**/*.md
    ignore:
      - '*.af.md'
      - '*.de.md'
      - '*.cs.md'
      - '*.en.md'
      - '*.es.md'
      - '*.fr.md'
      - '*.id.md'
      - '*.it.md'
      - '*.ja.md'
      - '*.ko.md'
      - '*.pl.md'
      - '*.pt.md'
      - '*.pt-BR.md'
      - '*.ru.md'
      - '*.sv.md'
      - '*.tr.md'
      - '*.uk.md'
      - '*.zh.md'
      - '/docs/release_notes/8.5.md'
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
    update_option: update_as_unapproved
