---
extends: existence
level: suggestion
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/oxfordcomma/
message: "Use the Oxford comma in '%s'."
# source: "IBM - Commas between clauses, p.45"
tokens:
  - '(?:[^,]+,){1,}\s\w+\sand'
