---
extends: substitution
ignorecase: false
level: suggestion
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/releasenotes/
message: "For release notes, consider using '%s' rather than '%s'."
# source: "https://redhat-documentation.github.io/supplementary-style-guide/#release-notes"
# swap maps tokens in form of bad: good
swap:
  Now: With this update
  Previously: Before this update
