---
extends: existence
level: error
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/spacing/
message: "Keep one space between words in '%s'."
nonword: true
# source: https://docs.microsoft.com/en-us/style-guide/punctuation/periods
tokens:
  - "[a-z][.?!] {2,}[A-Z]"
  - "[a-z][.?!][A-Z]"
