---
extends: substitution
ignorecase: false
level: suggestion
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/termssuggestions/
message: "Depending on the context, consider using '%s' rather than '%s'."
# source: "https://redhat-documentation.github.io/supplementary-style-guide/#glossary-terms-conventions; IBM - Appendix C. Word usage, p. 300"
action:
  name: replace
swap:
  "(?<!,) which": ", which (non restrictive clause preceded by a comma)|that (restrictive clause without a comma)"
  "(?<!by) using": by using|that uses
  "(?<!such )as": because|while
  ", that": ", which (non restrictive clause preceded by a comma)|that (restrictive clause without a comma)"
  "[Bb]are metal|[Bb]are-metal(?! clusters?| compute| configuration| controls?| environments?| equipment| events?| hardware| hosts?| infrastructure| installations?| installers?| machines?| media| nodes?| provisioning| servers?| workers?)": bare metal (noun)|bare-metal (adjective)
  "shell(?! prompt| script)": shell prompt
  and so on: "appropriate descriptive wording, unless you list a clear sequence of elements"
  between: " - ' to indicate a 'range of numbers"
  Bps|bps: Bps (bytes per second)|bps (bits per second)
  CD|cd: cd (change directory command)|CD (compact disc)
  channel: repository
  client side|client-side: client-side (adjective)| client side (noun)
  Cloud: cloud
  code: write
  crash: fail|lock up|stop|stop responding
  functionality: functions # IBM
  Hammer|x86_64|x86-64|x64|64-bit x86: AMD64
  input|type: enter (followed by the text to enter in monospace) # https://redhat-documentation.github.io/supplementary-style-guide/#text-entry
  jar: compress|archive (verb)
  Navigate|navigate: '"click", "select", "browse", or "go to"'
  recommend: direct users to take the recommended action
  refer to: see
  roll-out|roll out|rollout: roll out (verb)|rollout (noun)
  Router: AMQ Interconnect
  segfault: segmentation fault
  tar: compress|archive
  thru|through: "' - ' (range)|by using|finished|completed"
  unjar: extract (verb)
  user space|userspace|user-space: user space (noun)| user-space (modifier)
  zip: compress
  information on: information about
