---
name: Build (Vercel)
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
    
jobs:
  vercel_trigger:
    name: Vercel Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Hit the webhook
        run: curl ${{ secrets.VERCEL_DEPLOY_HOOK }}
