name: Create monthly release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=tag::$(date +'%b-%Y')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: "${{ steps.date.outputs.tag }}"
